name: boxjumps
root: ~/code/boxjumps/

startup_window: editor

windows:
  - editor:
      layout: main-horizontal
      panes:
        - vim
        -
  - server:
      layout: main-horizontal
      panes:
        - bundle exec rails server
        -
  - shell:
