# Mutt && offlineimap setup

name: email
root: ~/Desktop

startup_window: personal

windows:
  - personal: LOCAL_CONFIG=personal neomutt
  - work: LOCAL_CONFIG=work neomutt
  - offlineimap: offlineimap
